### ISSUE TITLE
Hey! This looks pretty sweet!

### ISSUE THREAD

**Issue by spences10** [0phoff/MDXP#2]
I was searching for something that wasn't MDX Deck and found this!

Looks like you have done a great job here than you so much, I was just trying to get my head around if I could import [MDX Embed] into this, I'm guessing I have to do it on a slide by slide basis?

Like with the [wrapper components]?	

[wrapper components]: https://0phoff.github.io/MDXP/guide-components#wrapper-components
[mdx embed]: https://github.com/PaulieScanlon/mdx-embed

**Comment by 0phoff** [comment]
Hey, thanks for your interest in MDXP!  
I kinda lost track of this project (still use almost weekly to create presentations though), but I will get back to it soon and fix some annoying things I noticed!

Now for MDX Embed, I don't really think you need anything special, seeing as [one of their examples](https://www.mdx-embed.com/?path=/docs/mdx-embed--page#alternatively) literally is to include their components into MDX.

I did not test anything, but I guess you have 2 options:
1. Add the MDX Embed components to the MDXProvider. You can do this with the `components` argument of [Deck](https://0phoff.github.io/MDXP/core-components#deck), which you can find in __src/index.jsx__, provided you used the webpack template.
2. Adding the components to the MDXProvider, simply means you do not need to import them into your MDX files. Unless they do something weird (eg. intialisation code) when importing the components, you should be able to import them straight in your MDX files as well:

```jsx
import { CodePen } from 'mdx-embed';

# Slide 1

<CodePen />

---

```

Let me know if you have any other problems!

**Comment by spences10** [comment]
I used MDX Embed np, here's the presentation: https://i-have-a-hammer.vercel.app/#/normal/0/0

Sauce: https://github.com/spences10/i-have-a-hammer/

**Comment by 0phoff** [comment]
Thanks for sharing! Do you mind if I add it to the examples page ? :innocent:

**Comment by spences10** [comment]
Yeah, no probs
