### ISSUE TITLE
Install error "create-webpack: command not found"

### ISSUE THREAD

**Issue by makkabi** [0phoff/MDXP#4]
Looks excellent, but I can't even install the starter project (macOS 11.2.3, M1 MacBook Pro), since I'm getting an "sh: create-webpack: command not found" error. The whole log is below. I tried both npx @mdxp/create-webpack -g my_presentation and npm init @mdxp/webpack -g my_presentation.

0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'init',
0 verbose cli   '@mdxp/webpack',
0 verbose cli   '-g',
0 verbose cli   'my_presentation'
0 verbose cli ]
1 info using npm@7.4.0
2 info using node@v15.6.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/wwb/Projekte/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/wwb/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 6ms
19 verbose npm-session 4230e4fb0393ad0e
20 timing npm:load Completed in 13ms
21 http fetch GET 200 https://registry.npmjs.org/@mdxp%2fcreate-webpack 12ms (from cache)
22 timing arborist:ctor Completed in 1ms
23 timing arborist:ctor Completed in 0ms
24 timing command:exec Completed in 103ms
25 timing command:init Completed in 130ms
26 verbose stack Error: command failed
26 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
26 verbose stack     at ChildProcess.emit (node:events:379:20)
26 verbose stack     at maybeClose (node:internal/child_process:1065:16)
26 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:296:5)
27 verbose cwd /Users/wwb/Projekte
28 verbose Darwin 20.3.0
29 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "init" "@mdxp/webpack" "-g" "my_presentation"
30 verbose node v15.6.0
31 verbose npm  v7.4.0
32 error code 127
33 error path /Users/wwb/Projekte
34 error command failed
35 error command sh -c create-webpack "my_presentation"
36 verbose exit 127

**Comment by 0phoff** [comment]
Could this be similar to [this issue](https://github.com/facebook/create-react-app/issues/3240) ?
I'm not a big npm/npx expert, but I am pretty sure I got this create-webpack command working on linux,mac and windows before.

Let me know how things go...

**Comment by portenez** [comment]
I'm having the same issue. I can notice from the verbose output that the `npm` version used by @makkabi is `7.4.x`. I am using `npm` version `7.6.3`

**Comment by AntonyFagundez** [comment]
Hi @0phoff I tryed with the version of example and works well.

Any change of dependencies? Maybe a download the versions its a workaround.

**Comment by hszhsh** [comment]
I had the same issue. Then I executed the command `npm i -g @mdxp/create-webpack`, and it worked.

**Comment by makkabi** [comment]
I got it installed after globally installing ```npm i -g @mdxp/create-webpack```, as @hszhsh recommended. But before that, the inital issue was still there, with both commands in the recommended section of "Getting started". I can't exactly tell when and why it worked, but I definitely had a few issues, and recommend testing the recommended commands on a "clean" system.

**Comment by felixroos** [comment]
It will also work with a local installation using `npm i -g @mdxp/create-webpack` then running the init command. would be nice if the docs mentioned any of this

**Comment by 0phoff** [comment]
Added extra note about installing `@mdxp/create-webpack`  in the readme
