### ISSUE TITLE
Support React 17 as a peer dependency

### ISSUE THREAD

**Issue by BenoitAverty** [0phoff/MDXP#5]
Hello !
I can't install mdxp in my app that uses React 17 (unless I install --force).

Would it be possible to add React 17 in the list of supported versions for React as a peer dependency ?

I know this isn't a common use case, but MDXP is the only react presentation library that I can use somewhat easily *inside* another app (and with MDX). And since React 17 has very few breaking changes, this shouldn't be too risky.

**Comment by 0phoff** [comment]
I cannot guarantee MDXP will work correctly with React 17, as I never tested this.
Thus not allowing React 17, which is a major release, (without `--force`), is exactly the behaviour I want.  
If you are willing to try running MDXP with React 17, you should use the `--force` arguments, which is exactly what it is meant for.

I don't have a lot of time to work on MDXP right now, but once I do, I will probably go through the entire codebase and try to update each of the packages to their newest versions.
